### ISSUE TITLE
Unnecessary class

### ISSUE THREAD

**Issue by Ryzeon** [Elb1to/SoupPvP#6]
![image](https://user-images.githubusercontent.com/60982533/118220279-f23e2e00-b440-11eb-84e3-d366b79b6dd8.png)
![image](https://user-images.githubusercontent.com/60982533/118220281-f407f180-b440-11eb-99d2-b93e8326195e.png)

**Comment by Elb1to** [comment]
Already fixed yesterday, didn't push the commit yet
